// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID        string  `json:"id"`
	PostID    string  `json:"postId"`
	ParentID  *string `json:"parentId,omitempty"`
	Content   string  `json:"content"`
	UserID    string  `json:"userId"`
	CreatedAt string  `json:"createdAt"`
}

type Mutation struct {
}

type Post struct {
	ID            string `json:"id"`
	Title         string `json:"title"`
	Content       string `json:"content"`
	UserID        string `json:"userId"`
	AllowComments bool   `json:"allowComments"`
	CreatedAt     string `json:"createdAt"`
}

type Query struct {
}
